import React from 'react';
import { Activity, Leaf, MessageCircle, ArrowRight, Users, IndianRupee, WifiOff, Globe, CheckCircle2, HeartPulse } from 'lucide-react';
import { motion } from 'framer-motion';

const sports = ['Cricket', 'Football', 'Kabaddi', 'Athletics', 'Wrestling', 'Kho-Kho', 'Hockey'];

const Dashboard = ({ language, setActiveTab }) => {
  const isEn = language === 'en';

  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0 }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 md:px-8 py-12">
      {/* Hero Section */}
      <div className="flex flex-col lg:flex-row items-center gap-12 lg:gap-16 mb-20">
        
        {/* Left: Text & CTA */}
        <motion.div 
          initial={{ opacity: 0, x: -30 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5 }}
          className="flex-1 text-center lg:text-left"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-xs font-semibold mb-6">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-blue-500"></span>
            </span>
            {isEn ? 'Now Available Nationwide' : 'अब देश भर में उपलब्ध'}
          </div>
          
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 leading-tight tracking-tight">
            {isEn ? 'Your Personal Sports Coach & Doctor — ' : 'आपका व्यक्तिगत खेल कोच और डॉक्टर — '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-emerald-400">
              {isEn ? 'Free, Forever' : 'हमेशा के लिए मुफ़्त'}
            </span>
          </h1>
          
          <p className="text-lg md:text-xl text-muted mb-10 max-w-2xl mx-auto lg:mx-0">
            {isEn ? "Built for 500 million Indian athletes who can't afford professional guidance. Get AI-powered triage, nutrition, and 24/7 coaching." : "50 करोड़ भारतीय एथलीटों के लिए बनाया गया जो पेशेवर मार्गदर्शन का खर्च नहीं उठा सकते।"}
          </p>
          
          <div className="flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-4 mb-12">
            <button 
              onClick={() => setActiveTab('injury')}
              className="w-full sm:w-auto px-8 py-4 rounded-xl bg-primary hover:bg-blue-600 text-white font-medium flex items-center justify-center gap-2 transition-all shadow-[0_0_20px_rgba(59,130,246,0.3)] hover:shadow-[0_0_30px_rgba(59,130,246,0.5)] hover:-translate-y-1"
            >
              {isEn ? 'Check an Injury' : 'चोट की जांच करें'} <ArrowRight className="w-5 h-5" />
            </button>
            <button 
              onClick={() => setActiveTab('nutrition')}
              className="w-full sm:w-auto px-8 py-4 rounded-xl bg-surface border border-border hover:bg-border hover:text-white text-gray-300 font-medium flex items-center justify-center gap-2 transition-all hover:-translate-y-1"
            >
              {isEn ? 'Get Meal Plan' : 'भोजन योजना प्राप्त करें'}
            </button>
          </div>
        </motion.div>

        {/* Right: Floating Visual / Mockup */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.9, x: 30 }}
          animate={{ opacity: 1, scale: 1, x: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="flex-1 w-full max-w-md lg:max-w-none relative mt-12 lg:mt-0"
        >
          <div className="relative w-full max-w-[340px] mx-auto h-[580px] flex items-center justify-center">
            
            {/* Center Glow */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-72 h-72 bg-primary/30 rounded-full blur-[80px]"></div>
            
            {/* Back Card: Nutrition (Rotated Right) */}
            <motion.div 
              animate={{ y: [0, -15, 0], rotate: [8, 10, 8] }} 
              transition={{ duration: 6, repeat: Infinity, ease: "easeInOut" }}
              className="absolute -right-6 sm:-right-12 top-20 w-56 sm:w-64 bg-surface/90 backdrop-blur-md border border-[#1E3A5F] rounded-2xl p-4 shadow-2xl z-0"
            >
              <div className="flex items-center gap-3 mb-4 border-b border-border pb-3">
                <div className="p-2 bg-secondary/10 rounded-lg"><Leaf className="w-4 h-4 text-secondary"/></div>
                <div>
                  <div className="text-sm font-bold text-gray-200">Pre-Match Meal</div>
                  <div className="text-[10px] text-muted">Generated by AI</div>
                </div>
              </div>
              <div className="space-y-3">
                <div className="flex justify-between text-[10px] text-gray-400 mb-1">
                  <span>Protein Target</span><span>45g</span>
                </div>
                <div className="h-1.5 w-full bg-background border border-border rounded-full overflow-hidden">
                  <div className="h-full bg-secondary w-[85%] rounded-full shadow-[0_0_10px_rgba(16,185,129,0.8)]"></div>
                </div>
              </div>
            </motion.div>

            {/* Main Center: Phone Mockup */}
            <motion.div 
              animate={{ y: [0, 15, 0] }} 
              transition={{ duration: 5, repeat: Infinity, ease: "easeInOut" }}
              className="relative w-[280px] h-[540px] bg-[#0A0F1E] border-[8px] border-[#16243A] rounded-[2.5rem] shadow-[0_0_50px_rgba(59,130,246,0.25)] overflow-hidden z-10 flex flex-col"
            >
              {/* Phone Notch */}
              <div className="absolute top-0 inset-x-0 h-6 flex justify-center z-20">
                <div className="w-24 h-6 bg-[#16243A] rounded-b-xl"></div>
              </div>
              
              {/* Phone Screen Content (Mini Chat) */}
              <div className="flex-1 pt-10 px-4 pb-4 flex flex-col bg-gradient-to-b from-[#0A0F1E] to-surface">
                <div className="flex items-center gap-2 mb-6">
                  <div className="w-8 h-8 rounded-full bg-primary/20 border border-primary/30 flex items-center justify-center">
                    <Activity className="w-4 h-4 text-primary" />
                  </div>
                  <div className="flex flex-col">
                    <span className="text-xs font-bold text-gray-200">AthleteEdge Doctor</span>
                    <span className="text-[9px] text-emerald-400 flex items-center gap-1">
                      <span className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-pulse"></span> Online
                    </span>
                  </div>
                </div>
                
                <div className="flex flex-col gap-3">
                  <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.5 }} className="self-end bg-primary text-white text-[10px] px-3 py-2 rounded-2xl rounded-tr-sm max-w-[85%] shadow-md">
                    I have sharp pain in my right knee after sprinting.
                  </motion.div>
                  <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 1 }} className="self-start bg-background border border-[#1E3A5F] text-gray-200 text-[10px] px-3 py-2 rounded-2xl rounded-tl-sm max-w-[95%] shadow-lg">
                    <span className="text-amber-500 font-bold block mb-1">Triage: MODERATE</span>
                    Stop running immediately. Apply ice for 15 mins. Based on your profile, this could be runner's knee.
                  </motion.div>
                  <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 2.5 }} className="self-end bg-primary text-white text-[10px] px-3 py-2 rounded-2xl rounded-tr-sm max-w-[85%] mt-1 shadow-md">
                    Should I see a doctor?
                  </motion.div>
                  <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 3.5 }} className="self-start bg-background border border-[#1E3A5F] text-gray-200 text-[10px] px-3 py-2 rounded-2xl rounded-tl-sm max-w-[40%] shadow-lg">
                    <div className="flex gap-1 items-center justify-center h-4">
                      <span className="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce"></span>
                      <span className="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce" style={{animationDelay: '0.2s'}}></span>
                      <span className="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce" style={{animationDelay: '0.4s'}}></span>
                    </div>
                  </motion.div>
                </div>
                
                {/* Fake Input */}
                <div className="mt-auto bg-background border border-[#1E3A5F] rounded-full h-10 flex items-center px-3 shadow-inner">
                  <div className="text-[10px] text-muted">Type a message...</div>
                  <div className="ml-auto w-6 h-6 rounded-full bg-primary flex items-center justify-center shadow-[0_0_10px_rgba(59,130,246,0.5)]">
                    <ArrowRight className="w-3 h-3 text-white" />
                  </div>
                </div>
              </div>
            </motion.div>

            {/* Front Card: Triage Badge (Rotated Left) */}
            <motion.div
              animate={{ y: [0, -10, 0], rotate: [-6, -4, -6] }} 
              transition={{ duration: 4.5, repeat: Infinity, ease: "easeInOut" }}
              className="absolute left-[-10px] sm:-left-8 bottom-32 w-48 sm:w-52 bg-surface/90 backdrop-blur-md border border-emerald-500/30 rounded-xl p-3 shadow-[0_0_30px_rgba(16,185,129,0.15)] z-20"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-emerald-500/10 rounded-full flex items-center justify-center border border-emerald-500/20">
                  <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                </div>
                <div>
                  <div className="text-xs font-bold text-emerald-400 uppercase tracking-wide">Cleared to Play</div>
                  <div className="text-[10px] text-gray-400">Recovery complete</div>
                </div>
              </div>
            </motion.div>

          </div>
        </motion.div>
      </div>

      {/* Stats Bar */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.3 }}
        className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm font-medium text-muted bg-surface/50 border border-border p-4 rounded-2xl mx-auto max-w-4xl backdrop-blur-sm mb-20 shadow-lg"
      >
        <div className="flex flex-col sm:flex-row items-center justify-center gap-2 p-2">
          <Users className="w-5 h-5 text-primary" />
          <div className="flex flex-col sm:items-start items-center">
            <span className="text-white text-lg font-bold leading-none">500M+</span>
            <span className="text-xs">{isEn ? 'Athletes' : 'एथलीट'}</span>
          </div>
        </div>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-2 p-2 border-l-0 md:border-l border-border/50">
          <IndianRupee className="w-5 h-5 text-emerald-400" />
          <div className="flex flex-col sm:items-start items-center">
            <span className="text-emerald-400 text-lg font-bold leading-none">₹0</span>
            <span className="text-xs">{isEn ? 'Cost' : 'लागत'}</span>
          </div>
        </div>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-2 p-2 border-t md:border-t-0 md:border-l border-border/50">
          <WifiOff className="w-5 h-5 text-purple-400" />
          <div className="flex flex-col sm:items-start items-center">
            <span className="text-white text-lg font-bold leading-none">24/7</span>
            <span className="text-xs">{isEn ? 'Works Offline' : 'ऑफ़लाइन'}</span>
          </div>
        </div>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-2 p-2 border-t border-l-0 md:border-t-0 md:border-l border-border/50">
          <Globe className="w-5 h-5 text-amber-400" />
          <div className="flex flex-col sm:items-start items-center">
            <span className="text-white text-lg font-bold leading-none">6</span>
            <span className="text-xs">{isEn ? 'Languages' : 'भाषाएँ'}</span>
          </div>
        </div>
      </motion.div>

      {/* Feature Cards */}
      <motion.div 
        variants={containerVariants}
        initial="hidden"
        animate="show"
        className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16"
      >
        <motion.div 
          variants={itemVariants}
          whileHover={{ y: -8, scale: 1.02 }}
          onClick={() => setActiveTab('injury')}
          className="bg-surface border border-border rounded-2xl p-8 cursor-pointer transition-all group relative overflow-hidden shadow-lg hover:shadow-[0_0_20px_rgba(59,130,246,0.15)] hover:border-primary/50"
        >
          <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 rounded-full blur-3xl -mr-10 -mt-10 transition-all group-hover:bg-primary/20"></div>
          <div className="flex justify-between items-start mb-6 relative z-10">
            <div className="p-4 bg-primary/10 rounded-xl text-primary border border-primary/20">
              <Activity className="w-8 h-8" />
            </div>
            <span className="text-[10px] font-bold px-3 py-1 bg-primary/20 text-primary border border-primary/30 rounded-full uppercase tracking-wider">
              {isEn ? 'AI Triage' : 'AI ट्राइएज'}
            </span>
          </div>
          <h3 className="text-2xl font-bold mb-3 group-hover:text-primary transition-colors relative z-10">
            {isEn ? 'Injury Recovery' : 'चोट से उबरना'}
          </h3>
          <p className="text-muted text-sm leading-relaxed relative z-10">
            {isEn ? 'Get immediate triage, recovery days, and personalized rehab exercises for your sports injuries instantly.' : 'अपनी खेल चोटों के लिए तत्काल ट्राइएज, रिकवरी के दिन और रिहैब व्यायाम प्राप्त करें।'}
          </p>
        </motion.div>

        <motion.div 
          variants={itemVariants}
          whileHover={{ y: -8, scale: 1.02 }}
          onClick={() => setActiveTab('nutrition')}
          className="bg-surface border border-border rounded-2xl p-8 cursor-pointer transition-all group relative overflow-hidden shadow-lg hover:shadow-[0_0_20px_rgba(16,185,129,0.15)] hover:border-secondary/50"
        >
          <div className="absolute top-0 right-0 w-32 h-32 bg-secondary/5 rounded-full blur-3xl -mr-10 -mt-10 transition-all group-hover:bg-secondary/20"></div>
          <div className="flex justify-between items-start mb-6 relative z-10">
            <div className="p-4 bg-secondary/10 rounded-xl text-secondary border border-secondary/20">
              <Leaf className="w-8 h-8" />
            </div>
            <span className="text-[10px] font-bold px-3 py-1 bg-secondary/20 text-secondary border border-secondary/30 rounded-full uppercase tracking-wider">
              {isEn ? 'Local Diet' : 'भारतीय भोजन'}
            </span>
          </div>
          <h3 className="text-2xl font-bold mb-3 group-hover:text-secondary transition-colors relative z-10">
            {isEn ? 'Nutrition Planner' : 'पोषण योजनाकार'}
          </h3>
          <p className="text-muted text-sm leading-relaxed relative z-10">
            {isEn ? 'Generate custom, budget-friendly meal plans based on your sport and local Indian ingredients.' : 'स्थानीय भारतीय आहार का उपयोग करके अपने खेल, लक्ष्य और बजट के आधार पर कस्टम भोजन योजनाएं।'}
          </p>
        </motion.div>

        <motion.div 
          variants={itemVariants}
          whileHover={{ y: -8, scale: 1.02 }}
          onClick={() => setActiveTab('chat')}
          className="bg-surface border border-border rounded-2xl p-8 cursor-pointer transition-all group relative overflow-hidden shadow-lg hover:shadow-[0_0_20px_rgba(96,165,250,0.15)] hover:border-blue-400/50"
        >
          <div className="absolute top-0 right-0 w-32 h-32 bg-blue-500/5 rounded-full blur-3xl -mr-10 -mt-10 transition-all group-hover:bg-blue-500/20"></div>
          <div className="flex justify-between items-start mb-6 relative z-10">
            <div className="p-4 bg-blue-500/10 rounded-xl text-blue-400 border border-blue-500/20">
              <MessageCircle className="w-8 h-8" />
            </div>
            <span className="text-[10px] font-bold px-3 py-1 bg-blue-500/20 text-blue-400 border border-blue-500/30 rounded-full uppercase tracking-wider">
              {isEn ? '24/7 Access' : '24/7'}
            </span>
          </div>
          <h3 className="text-2xl font-bold mb-3 group-hover:text-blue-400 transition-colors relative z-10">
            {isEn ? 'Coach & Doctor' : 'कोच और डॉक्टर चैट'}
          </h3>
          <p className="text-muted text-sm leading-relaxed relative z-10">
            {isEn ? 'Ask questions anytime. Switch between Coach mode for performance and Doctor mode for medical advice.' : 'कभी भी प्रश्न पूछें। प्रदर्शन के लिए कोच और चिकित्सा सलाह के लिए डॉक्टर के बीच स्विच करें।'}
          </p>
        </motion.div>
      </motion.div>

      <div className="text-center pt-8 border-t border-border/50 max-w-4xl mx-auto">
        <p className="text-xs text-muted mb-6 uppercase tracking-[0.2em] font-semibold">{isEn ? 'Supported Sports' : 'लोकप्रिय खेल'}</p>
        <div className="flex flex-wrap justify-center gap-3">
          {sports.map((sport, i) => (
            <motion.div 
              key={sport} 
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.5 + (i * 0.05) }}
              className="px-5 py-2.5 rounded-full bg-surface border border-border text-sm text-gray-300 hover:bg-background hover:text-white hover:border-primary/40 transition-all cursor-default shadow-sm"
            >
              {sport}
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
